### ISSUE TITLE
How to build on Ubuntu?

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/Industrial-IoT-Gateway-Installer#10]
Sorry if I missed this somewhere, but where are the prereqs, setup and build instructions for Ubuntu?

**Comment by barnstee** [comment]
You don't need to build it for Ubuntu, the prebuilt release is here: https://github.com/Azure/Industrial-IoT-Gateway-Installer/tree/master/Releases
If you want to still build it, I recommend using Visual Studio Code on Ubuntu.

**Comment by RotateAt60MPH** [comment]
Great!  Thanks for the quick response!

**Comment by RotateAt60MPH** [comment]
I found the Linux.zip file, which I assumed was the build files, but there is no executable in there.  Looks like the linux libraries are there (*.so), but doesn't appear to be anything to run...?  ;)

**Comment by RotateAt60MPH** [comment]
Thanks!
