### ISSUE TITLE
Error when performing install on Ubuntu 18.04 fresh install

### ISSUE THREAD

**Issue by etf5000** [Azure/Industrial-IoT-Gateway-Installer#13]
When executing the dotnet IoTEdgeInstallerConsoleApp.dll  I receive the following error:

Setting up iotedge (1.0.8-2) ...
===============================================================================

                              Azure IoT Edge

  IMPORTANT: Please update the configuration file located at:

    /etc/iotedge/config.yaml

  with your device's provisioning information. You will need to restart the
  'iotedge' service for these changes to take effect.

  To restart the 'iotedge' service, use:

    'systemctl restart iotedge'

    - OR -

    /etc/init.d/iotedge restart

  These commands may need to be run with sudo depending on your environment.

===============================================================================
Created symlink /etc/systemd/system/sockets.target.wants/iotedge.mgmt.socket → /lib/systemd/system/iotedge.mgmt.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/iotedge.service → /lib/systemd/system/iotedge.service.
Created symlink /etc/systemd/system/sockets.target.wants/iotedge.socket → /lib/systemd/system/iotedge.socket.
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.24) ...
sed: -e expression #1, char 144: unknown option to `s'
A dependency job for iotedge.service failed. See 'journalctl -xe' for details.

This part of the installation is completed.
Please restart your system to complete the installation.

Press Enter to exit.

journalctl shows the following:

Apr 22 20:30:14 hou-vir-lnx-iot-01 sudo[5476]: pam_unix(sudo:session): session closed for user root
Apr 22 20:30:14 hou-vir-lnx-iot-01 sudo[6467]:     root : TTY=pts/0 ; PWD=/home/otlab/PortableConsole ; USER=root ; COMMAND=/bin/sed -i s/<ADD DEVICE CONNECTION STRING HERE>/HostName=iothub-gapxw.azure-devices.net;DeviceId=hou-vir-lnx-iot-01;SharedAccessKey=9**REMOVED**E=/g /etc/iotedge/config.yaml
Apr 22 20:30:14 hou-vir-lnx-iot-01 sudo[6467]: pam_unix(sudo:session): session opened for user root by otlab(uid=0)
Apr 22 20:30:14 hou-vir-lnx-iot-01 sudo[6467]: pam_unix(sudo:session): session closed for user root

**Comment by barnstee** [comment]
This is not an error but normal output of the Edge installer script. /etc/iotedge/config.yaml id automatically updated.

**Comment by barnstee** [comment]
Close due to lack of response.
