### ISSUE TITLE
OPC Twin & Publisher Modules Not Being Installed

### ISSUE THREAD

**Issue by erlendp** [Azure/Industrial-IoT-Gateway-Installer#14]
The documentation mentions that these two modules can be optionally installed by the installer, but this doesn't seem to be the case. After installation, I'm seeing a configuration error in IoT Hub, which only goes away once manually adding these two modules via the portal.

Is this expected behaviour?

**Comment by barnstee** [comment]
Yes, sorry, we changed the installer to be compatible with the new Azure Industrial IoT cloud platform as well as IoT Central, which have a different mechanism to install the industrial modules (so-called "automatic deployment", see here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-at-scale). So if you want to use the installer stand-alone, you need to manually add the modules yourself. I'll change the docs to make that clear.

**Comment by barnstee** [comment]
Fixed.
