### ISSUE TITLE
IoTEdgeInstallerConsoleApp replace string escape

### ISSUE THREAD

**Issue by AiHaibara** [Azure/Industrial-IoT-Gateway-Installer#16]
`$"sudo sed -i 's/<ADD DEVICE CONNECTION STRING HERE>/HostName={iotHub.Name}.azure-devices.net;DeviceId={deviceEntity.Id};SharedAccessKey={deviceEntity.Authentication.SymmetricKey.PrimaryKey}/g' /etc/iotedge/config.yaml".Bash();`
the hmac256 hash algorithm sometimes will generate the connectionstring contains the '/' character, will always install failed with that device name.
so, the device connection string value should be escape.
replace '/' to '\\/' for the PrimaryKey first.
or replace the '/' to '!' 
`$"sudo sed -i 's!<ADD DEVICE CONNECTION STRING HERE>!HostName={iotHub.Name}.azure-devices.net;DeviceId={deviceEntity.Id};SharedAccessKey={deviceEntity.Authentication.SymmetricKey.PrimaryKey}!g' /etc/iotedge/config.yaml".Bash();`

**Comment by barnstee** [comment]
Thanks for calling this out, @AiHaibara, I'll have a look...

**Comment by barnstee** [comment]
Fixed with https://github.com/Azure/Industrial-IoT-Gateway-Installer/commit/a325fe9c6775d075046e546f4d0b72923448e23b
