### ISSUE TITLE
Checking for hyper-v does not work on Windows (Windows Server 2019 Datacenter)

### ISSUE THREAD

**Issue by kbasgall** [Azure/Industrial-IoT-Gateway-Installer#17]
Hi!
I'm trying to use this installer in an Azure Virtual Machine running Windows (Windows Server 2019 Datacenter).  When the installer checks for hyper-v, it runs:
```bash
Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
```

However, this feature name does not exist in the VM.  In this version, it is just called `Microsoft-Hyper-V`.  Here is some output from the VM:
```bash 
PS C:\Users\kepwareadmin> Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
PS C:\Users\kepwareadmin> Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online


FeatureName      : Microsoft-Hyper-V
DisplayName      : Hyper-V
Description      : Hyper-V
RestartRequired  : Possible
State            : Enabled
CustomProperties : /* properties omitted */

PS C:\Users\kepwareadmin>
```

Note, I have run the same commands on my local machine which is running Windows 11, and they both produce output.

I want the installer to check both of these package names so Windows Server is supported in addition to Windows 10.

**Comment by barnstee** [comment]
Fixed with checkin https://github.com/Azure/Industrial-IoT-Gateway-Installer/commit/447058c2c3c13c92d2127c856af36572348a30f7
